apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration-app
  namespace: registration-js
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registration-app
  template:
    metadata:
      labels:
        app: registration-app
    spec:
      containers:
      - name: registration-app
        image: masum012924/registration-app:v3
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: db
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB

---
apiVersion: v1
kind: Service
metadata:
  name: registration-app-service
  namespace: registration-js
spec:
  selector:
    app: registration-app
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort

