apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-registration-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/masumshamsur/user_registration_js-PostgreSQL-Docker-K8S-Helm-GitHubAction-ArgoCD.git # Replace with your actual Git repository URL
    targetRevision: develop
    path: user-registration-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: registration-js
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
