apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-registration-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/user-registration-js-postgresql-docker-k8s-helm-githubaction-argocd  # Replace with your actual Git repository URL
    targetRevision: develop
    path: user-registration-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: registration-js
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true